#!/bin/bash


if [ $# != 1 ] || [[ $1 != +([0-9]) ]] || [ $1 == 0 ]; then
	echo "Need one argument : the number of exercices."
else
	for ((i = 0; i < $1; i++)); do
		mkdir "ex$((i / 10))$((i % 10))"
	done
fi
